### ISSUE TITLE
Feature request: list files/folders as list, not just icons

### ISSUE THREAD

**Issue by cipricus** [thevladsoft/transparentfolderview#2]
I prefer to see the files and folders as a list rather than a grid of icons. Ideally, the list would be similar to what we have in Dolphin, with details or without (in compact view).

[Is there some change that I can make in the widget files to get a list already?](https://www.reddit.com/r/kde/comments/1672rab/can_i_modify_transparent_folder_view_widget_so/?utm_source=share&utm_medium=web2x&context=3)

I am using the widget to get quickest access possible to recent files and locations on the desktop.

**Comment by thevladsoft** [comment]
Done, download v3.0

**Comment by cipricus** [comment]
thank you!
