### ISSUE TITLE
Refresh the recent files and locations

### ISSUE THREAD

**Issue by cipricus** [thevladsoft/transparentfolderview#4]
Your responsiveness gives me courage to annoy you with more requests in order to improve this very useful tool!

I have noticed that the list of files and folders _other than_ that of recent files or recent locations is _not_ affected: when I set the widget to list the "Downloads" folder, for example, and I then delete some files in that folder, the Transparent Folder view instantly reflects the change. (On the other hand, I haven't used the widget long enough that way to be absolutely sure these normal folders are never affected.) ­­– But  **_for recent files or recent locations, the list I see on the desktop is most of the time outdated_**, and it seems it can stay like that for days. 

First of all, I wanted to see if that's maybe Dolphin's fault, because [for all purposes Dolphin doesn't refresh often enough anyway](https://askubuntu.com/q/311303/925128) imo (the bug was mentioned [more recently](https://www.reddit.com/r/kde/comments/p0xvtt/dolphin_sometimes_doesnt_refresh_the_file_list/?utm_source=share&utm_medium=web2x&context=3) too). But in Dolphin refresh can be done quickly with a shortcut. The problem is that, **_after refreshing the recent files/location list in Dolphin, it is still not refreshed in the desktop widget_**.

I have noticed that I can refresh the recent files/locations widget list by entering the widget's settings and selecting "Icons" in the left panel: after a second it is refreshed.

So, what I'm asking is for the widget to refresh by itself more often somehow, if possible (that is, to trigger by itself that which I see when opening its settings and clicking "Icons" panel entry).

**Comment by thevladsoft** [comment]
The widget is dependent on plasma, not dolphin, so it's possible they do things on different ways. This is specially true for special folders, like recent files or recent folders. There is a way to refresh, however,  you can right and select "refresh (something)". That something will change if the widget is on the desktop or on a panel, etc. But the action is always the same.
Now, I can add a timer to make it force auto refresh more often. That could be a solution but it will have a small impact on the system, as it will force the system to do extra calls to the filesystem. 

So I think I will add it off by default. I little warning, though, I have tested and there is still some delay for "recent files" to update, but only of a few seconds.

**Comment by thevladsoft** [comment]
Done in V3.3

**Comment by cipricus** [comment]
> small impact on the system

It is indeed small, testing with a 5 sec refresh I see no spike in CPU graph. And a much bigger number can be used with no significant difference in view of my goal here. Thanks again!
