### ISSUE TITLE
Maybe the option "Hide icons with a double click in an empty area" should be disabled by default

### ISSUE THREAD

**Issue by cipricus** [thevladsoft/transparentfolderview#5]
(I say "maybe" because this is possibly more of a feature request or discussion, given that [some users](https://www.reddit.com/r/kde/comments/169org1/comment/jz3gcim/?utm_source=share&utm_medium=web2x&context=3) find the feature very useful, although I personally haven't guessed what its main use is supposed to be :))

For new users that haven't yet tinkered with the widget settings, having that enabled by default is very confusing, because the widget gets voided all of a sudden with no apparent reason. (I have found myself a few times re-installing the widget because I thought it was a bug.) 

Even for people that are aware of the feature, there may be no clear distinction between empty and non-empty area, so that, double clicking can lead to all entries being hidden. Then, trying to click again and get them back, it may again be difficult to see where that should be done.

**Comment by thevladsoft** [comment]
I already consider it when I added the option, but it made me think that it could affect the discoverability of it to have it of by default.

I will add a warning label, so new users can now what's going on, an disable if they want.
Funfact: I don't use the feature myself, but people that comes from windows seems to miss it.

**Comment by thevladsoft** [comment]
Done in V3.3
