### ISSUE TITLE
Add sorting option by "access" (not just "modification" time) - and possibly other options

### ISSUE THREAD

**Issue by cipricus** [thevladsoft/transparentfolderview#6]
_Sorry for my frequent posts!_
_Also, if you consider that this request should be limited to only one  of the two points, tell me, and I will edit to remove point 2._

There are two aspects to this feature request, first, the more specific, chronological aspect of listing (decisive for the recent files and folders), and, second, the general aspect of having more options available (while I'm personally only interested in the first, but the rest could be attractive to others):

1. The sorting by "Date" in the widget settings corresponds to the "Modified " column in  Dolphin: when sorting like that I only see listed files that have been _modified_, but not those that have been only _accessed without being modified_. Thus, I will see files that I have just saved, but not pdf, audio or video files that were present on my device and were just accessed. These will be listed only if they have also been recently created (downloaded by example).  But I personally work with a lot of existing files that I only access (read, view, listen to) without modifying them.  
![image](https://github.com/thevladsoft/transparentfolderview/assets/3447868/37b10717-ba3e-4333-aa28-72da23491fde)

_**For the purpose of accessing "recent files", I need  the "Accessed" criterion, not just the "Modified".**_

Given that "Accessed" category includes "Modified" category, **_it will serve my purpose to simply change the active criterion behind the "Date" sorting setting in the widget from what it is now into the "Accessed_**", if possible.

2. If possible (just as a suggestion, and according to what your would consider useful), add more options to the sorting settings, beside what we have now:
![image](https://github.com/thevladsoft/transparentfolderview/assets/3447868/9697ea8a-b1ad-488e-b1a9-3e5ab690717c)

**Comment by thevladsoft** [comment]
No can do. Again, this widget is based on an already existing widget of **plama**. Things that can be done on dolphin are not necessarily possible on it. Or it could be, but KDE's documentation is not very helpful in this sense. 
A quick search and some meddling with the code didn't allow me to implement what you ask, so I will close as not planed.

**Comment by cipricus** [comment]
I can use directly Dolphin to sort list by access, and there are _some_ menu launcher which do that by default, —most conspicuously good old Kicker— but also Onze Menu, Menu X, WQ Application Launcher.  Kickoff (the default Application Launcher) also sorts by access, but files and folders are listed together.

I will ask on Discuss maybe somebody comes with a helpful idea.

**Comment by cipricus** [comment]
I have asked here: https://discuss.kde.org/t/how-can-the-widget-transparent-folder-view-be-modified-in-order-to-list-recent-accessed-used-files-not-just-modified-ones/5012?u=cipricus

Feel free to suggest me changing that post if you think I should.

**Comment by cipricus** [comment]
You should close this, but for a different reason! :)

 Looking more into it I think I was completely wrong. The way the widget shows recent files just adds the _supplementary_ condition of listing them in order of their modification: but _it's still the same number of recently accessed files_.

Now I understand that `recentlyused:/files/` will always show recently _accessed_ files, it's just that Transparent Folder (like Dolphin's "Modified" column) will sort in order of their modification *or creation*. 

Something like `recentlyused:/files/?limit=35`, the last 35 most recently used files (modified by me or not) will be listed: and they will be sorted by date of change or creation in this widget. 

Recently accessed files cannot fail to appear in the list, the list is nothing but that: `recentlyused:/files/` is the sum of most recent (30) _accessed/used_ files — they are only _sorted_ by date of change/creation (in the widget or under "Modified" column). They are taken from the same - specific and adjustable - *number* of recently accessed files anyway: it's the same items, same number in both cases, only sorting differs.

So, after many files have been modified and then others have been just accessed, all the widget needs is to have a long-enough list for it to make visible the accessed-but-not-recently-modified files, as they are listed after the more recently modified..
